services:
  vault:
    ports:
      - ${VAULT_HTTP_PORT:?err}:${VAULT_HTTP_PORT:?err}
      - ${VAULT_HTTPS_PORT:?err}:${VAULT_HTTPS_PORT:?err}
      - ${VAULT_gRPC_PORT:?err}:${VAULT_gRPC_PORT:?err}
      - ${VAULT_gRPC_TLS_PORT:?err}:${VAULT_gRPC_TLS_PORT:?err}

  homepage:
    ports:
      - ${HOMEPAGE_HTTP_PORT:?err}:80
      - ${HOMEPAGE_HTTPS_PORT:?err}:443
    build:
      args:
        - SWOB_BE_HOST=https://${VAULT_HTTP_HOST}:${VAULT_HTTPS_PORT}
        - SWOB_GS_HOST=https://${GATEWAY_SERVER_HTTP_HOST}:${GATEWAY_SERVER_HTTPS_PORT}

  gateway-server:
    ports:
      - ${GATEWAY_SERVER_HTTP_PORT:?err}:${GATEWAY_SERVER_HTTP_PORT:?err}
      - ${GATEWAY_SERVER_HTTPS_PORT:?err}:${GATEWAY_SERVER_HTTPS_PORT:?err}
      - ${GATEWAY_SERVER_FTP_PORT:?err}:${GATEWAY_SERVER_FTP_PORT:?err}
      - ${GATEWAY_SERVER_FTP_PASSIVE_PORTS:?err}:${GATEWAY_SERVER_FTP_PASSIVE_PORTS:?err}

  publisher:
    ports:
      - ${PUBLISHER_gRPC_PORT:?err}:${PUBLISHER_gRPC_PORT:?err}
      - ${PUBLISHER_gRPC_TLS_PORT:?err}:${PUBLISHER_gRPC_TLS_PORT:?err}

  gateway-client-remote:
    ports:
      - ${GATEWAY_CLIENT_REMOTE_HTTP_PORT:?err}:${GATEWAY_CLIENT_REMOTE_HTTP_PORT:?err}
      - ${GATEWAY_CLIENT_REMOTE_HTTPS_PORT:?err}:${GATEWAY_CLIENT_REMOTE_HTTPS_PORT:?err}
