services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_defaults/security.conf:/etc/nginx/security.conf:ro
      - ${SSL_CERTIFICATES_PATH}:/etc/nginx/certs:ro
      - ./nginx_defaults/conf.d:/etc/nginx/conf.d:ro
    networks:
      - assembler_network

networks:
  assembler_network:
    driver: bridge
