services:
  portainer:
    restart: always
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ${SSL_CERTIFICATE_FILE:?err}:/certs/fullchain.pem
      - ${SSL_CERTIFICATE_KEY_FILE:?err}:/certs/privkey.pem
    command: --sslcert /certs/fullchain.pem --sslkey /certs/privkey.pem
    networks:
      - assembler_network

volumes:
  portainer_data:


networks:
  assembler_network:
    driver: bridge
