services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    depends_on:
      homepage:
        condition: service_started
      gateway-server:
        condition: service_started
      bridge-server:
        condition: service_started
      vault:
        condition: service_started
      publisher:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "15000:15000"
      - "9000:9000"
      - "8080:8080"
      - "7000:7000"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/security.conf:/etc/nginx/security.conf:ro
      - ./nginx/block-exploits.conf:/etc/nginx/block-exploits.conf:ro
      - ./nginx/templates:/etc/nginx/templates
      - ${SSL_CERTIFICATE_FILE:?err}:/etc/nginx/certs/${HOMEPAGE_HTTP_HOST}/fullchain.pem
      - ${SSL_CERTIFICATE_KEY_FILE:?err}:/etc/nginx/certs/${HOMEPAGE_HTTP_HOST}/privkey.pem
      - ${SSL_CERTIFICATE_CHAIN_FILE:?err}:/etc/nginx/certs/${HOMEPAGE_HTTP_HOST}/chain.pem
    env_file:
      - path: .env.default
        required: true
      - path: .env
        required: false
    networks:
      - assembler_network

networks:
  assembler_network:
    driver: bridge
