services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "15000:15000"
      - "9000:9000"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_defaults/security.conf:/etc/nginx/security.conf:ro
      - ./nginx_defaults/block-exploits.conf:/etc/nginx/block-exploits.conf:ro
      - ${SSL_CERTIFICATES_PATH}:/etc/nginx/certs:ro
    networks:
      - assembler_network

networks:
  assembler_network:
    driver: bridge
