x-environment: &glitchtip-default-environment
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${GLITCHTIP_POSTGRES_DB:-postgres}
  SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
  PORT: ${GLITCHTIP_PORT:-80}
  GLITCHTIP_DOMAIN: https://${GLITCHTIP_DOMAIN}
  CELERY_WORKER_AUTOSCALE: "1,3"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"
  EMAIL_HOST: ${GLITCHTIP_EMAIL_HOST}
  EMAIL_PORT: ${GLITCHTIP_EMAIL_PORT:-587}
  EMAIL_USE_TLS: ${GLITCHTIP_EMAIL_USE_TLS:-True}
  EMAIL_HOST_USER: ${GLITCHTIP_EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${GLITCHTIP_EMAIL_HOST_PASSWORD}
  DEFAULT_FROM_EMAIL: ${GLITCHTIP_DEFAULT_FROM_EMAIL}
  ENABLE_USER_REGISTRATION: False

x-depends_on: &glitchtip-default-depends_on
  - postgres
  - redis

services:
  database-cron-backup:
    restart: unless-stopped
    image: fradelg/mysql-cron-backup
    container_name: database-backup
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - database-backup-data:/backup
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MAX_BACKUPS=${DB_MAX_BACKUPS:-15}
      - INIT_BACKUP=0
      - EXIT_BACKUP=1
      - CRON_TIME=${DB_BACKUP_CRON_SCHEDULE:-0 3 * * *}
      - GZIP_LEVEL=9
      # As of MySQL 8.0.21 this is needed
      - MYSQLDUMP_OPTS=--no-tablespaces
    networks:
      - assembler_network

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - assembler_network

  redis:
    image: valkey/valkey
    container_name: redis
    restart: unless-stopped
    networks:
      - assembler_network

  glitchtip-web:
    image: glitchtip/glitchtip
    container_name: glitchtip-web
    depends_on: *glitchtip-default-depends_on
    environment: *glitchtip-default-environment
    restart: unless-stopped
    volumes:
      - glitchtip-uploads:/code/uploads
    networks:
      - assembler_network

  glitchtip-worker:
    image: glitchtip/glitchtip
    container_name: glitchtip-worker
    command: ./bin/run-celery-with-beat.sh
    depends_on: *glitchtip-default-depends_on
    environment: *glitchtip-default-environment
    restart: unless-stopped
    volumes:
      - glitchtip-uploads:/code/uploads
    networks:
      - assembler_network

  glitchtip-migrate:
    image: glitchtip/glitchtip
    container_name: glitchtip-migrate
    depends_on: *glitchtip-default-depends_on
    command: ./bin/run-migrate.sh
    environment: *glitchtip-default-environment
    networks:
      - assembler_network

volumes:
  database-backup-data:
  postgres-db-data:
  glitchtip-uploads:


networks:
  assembler_network:
    driver: bridge
